#!/bin/bash

if [[ "$MACHINE" != "home" ]]; then
	inputDevice='DELL07E6:00 06CB:76AF Touchpad'
else
	inputDevice='DELL097D:00 04F3:311C Touchpad'
fi

propId="libinput Tapping Enabled"
id=$(xinput --list --id-only "$inputDevice")
enabled=$(xinput list-props $id | grep "$propId" | head -n 1 | cut -d ':' -f 2 | grep -Eo '0|1')

color='"#00ffbb"'
char= # pointing finter
if [[ $enabled -eq 0 ]]; then
	color='"#888888"'
	char= # closed fist
fi

echo "<span color=$color> $char </span>"
