#!/bin/bash

propId="libinput Tapping Enabled"
id=$(xinput --list --id-only 'SynPS/2 Synaptics TouchPad')
enabled=$(xinput list-props $id | grep "$propId" | head -n 1 | cut -d ':' -f 2 | grep -Eo '0|1')

color='"#00ffbb"'
char= # pointing finter
if [[ $enabled -eq 0 ]]; then
	color='"#888888"'
	char= # closed fist
fi

echo "<span color=$color>$char</span>"
