#!/bin/bash

sdu='systemctl --user'

mode=
if $sdu is-active powerman@bat >/dev/null
then
	mode='bat'
else
	mode='ac'
fi

if [[ $BLOCK_BUTTON -eq 1 ]]; then
	if [[ "$mode" == "ac" ]]; then
		$sdu start powerman@bat
	else
		$sdu start powerman@ac
	fi
else
	echo $mode
fi
