#!/usr/bin/env python

import sys
import re

from datetime import datetime


pattern = re.compile(r"t:(\d{4})-(\d{2})-(\d{2})")
now = datetime.now()


def main(args=None):
	for line in sys.stdin:
		if in_future(line) or is_hidden(line):
			continue
		print(line.strip())
	return True

"""
filter incoming lines based on date threshold

hides tasks marked with a date threshold ("t:YYYY-MM-DD") in the future

this is intended to be used as TODOTXT_FINAL_FILTER
"""
def in_future(line):
	match = pattern.search(line)
	if match:
		threshold = [int(i) for i in match.groups()]
		if datetime(*threshold) < now:
			return False
	else:
		return False
	return True

def is_hidden(line):
	if "h:1" in line:
		return True
	return False

if __name__ == "__main__":
	status = not main(sys.argv)
	sys.exit(status)
