[manager]
  prepend_keymap = [
    { on   = "!", run  = 'shell "$SHELL" --block', desc = "Open shell here" },
    { on   = ["g", "."], run  = 'cd $HOME/.dotfiles', desc = "Goto ~/.dotfiles" },
  ]

[input]
  prepend_keymap = [
    { on   = "<Esc>", run  = "close", desc = "Cancel input" }
  ]
