#!/bin/sh
bl_dev=/sys/class/backlight/intel_backlight
step=100

case $1 in
  -) echo $(($(< $bl_dev/brightness) - $step)) >$bl_dev/brightness;;
  +) echo $(($(< $bl_dev/brightness) + $step)) >$bl_dev/brightness;;
esac

echo "$(cat $bl_dev/brightness)/$(cat $bl_dev/max_brightness)"
