#!/bin/sh
bl_dev=/sys/class/backlight/intel_backlight
if uname -a | grep Ubuntu >/dev/null; then
	step=500
else
	step=100
fi

case $1 in
  -) echo $(($(cat $bl_dev/brightness) - $step)) >$bl_dev/brightness;;
  +) echo $(($(cat $bl_dev/brightness) + $step)) >$bl_dev/brightness;;
esac

# update i3blocks
# pkill -RTMIN+2 i3blocks

# print brightness
# echo "$(cat $bl_dev/brightness)/$(cat $bl_dev/max_brightness)"

# notify brightness
bpct=$(echo "scale=2;$(cat /sys/class/backlight/intel_backlight/brightness)/$(cat /sys/class/backlight/intel_backlight/max_brightness)*100" | bc | sed -E -n 's/([0-9]+)\.?([0-9]*)/\1 %/p')
dunstify -a " Brightness" -t 2000 -r 2594 -u normal "$bpct"
