#!/bin/bash

dimmerLastBrightnessFile=$HOME/.local/lastbrightness
bl_dev=/sys/class/backlight/intel_backlight

if uname -a | grep Ubuntu >/dev/null; then
	step=500
else
	step=5000
fi

cur_brightness=$(cat $bl_dev/brightness)

case $1 in
  -)
		target_brightness=$(($cur_brightness - $step))
		if [[ $target_brightness -lt 0 ]]; then
			echo 0 >$bl_dev/brightness
		else
			echo $target_brightness>$bl_dev/brightness
		fi
		;;
  +)
		target_brightness=$(($cur_brightness + $step))
		max_brightness=$(cat $bl_dev/max_brightness)
		if [[ $target_brightness -gt $max_brightness ]]; then
			echo $max_brightness>$bl_dev/brightness
		else
			echo $target_brightness>$bl_dev/brightness
		fi
		;;
esac

## remove the file used for restoring brightness
## used by the dimmer if it exists. this way the dimmer
## script will change the brightness in an attempt to restore
## to the original brightness on idle exit
if [[ -f $dimmerLastBrightnessFile ]]; then
	rm $dimmerLastBrightnessFile
fi

## notify brightness
bpct=$(echo "scale=2;$(cat /sys/class/backlight/intel_backlight/brightness)/$(cat /sys/class/backlight/intel_backlight/max_brightness)*100" | bc | sed -E -n 's/([0-9]+)\.?([0-9]*)/\1 %/p')
dunstify -a " Brightness" -t 2000 -r 2594 -u normal "$bpct" -t 10
