#!/bin/bash

if uname -a | grep Ubuntu >/dev/null; then
	inputDevice='DELL07E6:00 06CB:76AF Touchpad'
else
	inputDevice='SynPS/2 Synaptics TouchPad'
fi

propId="libinput Tapping Enabled"
id=$(xinput --list --id-only "$inputDevice")
enabled=$(xinput list-props $id | grep "$propId" | head -n 1 | cut -d ':' -f 2 | grep -Eo '0|1')

newval=0
if [[ $enabled -eq 0 ]]; then
	newval=1
fi

echo "setting device $id tapping-enabled to $newval"

xinput set-prop $id "$propId" $newval
pkill -RTMIN+3 i3blocks
